### ISSUE TITLE
pip install fails from pypi but works from GitHub

### ISSUE THREAD

**Issue by CloudySnake** [haizaar/check-pipfile-lock#3]
Hey there,

Just stumbled across this library and am going to introduce it to my CI/CD pipelines.  Have a strange problem though, the library installs perfectly from GitHub directly, but if I try from pypi I get the error below

`    ERROR: Command errored out with exit status 1:
     command: /usr/local/opt/python/bin/python3.7 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/0z/6lp1s4fx7ylcpdy9clv4m00w0000gn/T/pip-install-5qksxyvw/check-pipfile-lock/setup.py'"'"'; __file__='"'"'/private/var/folders/0z/6lp1s4fx7ylcpdy9clv4m00w0000gn/T/pip-install-5qksxyvw/check-pipfile-lock/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /private/var/folders/0z/6lp1s4fx7ylcpdy9clv4m00w0000gn/T/pip-pip-egg-info-m7176oxq
         cwd: /private/var/folders/0z/6lp1s4fx7ylcpdy9clv4m00w0000gn/T/pip-install-5qksxyvw/check-pipfile-lock/
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/0z/6lp1s4fx7ylcpdy9clv4m00w0000gn/T/pip-install-5qksxyvw/check-pipfile-lock/setup.py", line 8, in <module>
        with open("LICENSE") as f:
    FileNotFoundError: [Errno 2] No such file or directory: 'LICENSE'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.`

I'm using Python 3.7 running MacOS if that helps.

**Comment by haizaar** [comment]
Good catch! Thank you for reporting this one.
Fixed on 4eef6ca. Released 0.0.4.

Please have a look and if all it working please close the bug.

**Comment by CloudySnake** [comment]
Thanks for this, I can pip install but I get a different error

`ERROR: Could not install packages due to an EnvironmentError: [Errno 13] Permission denied: '/usr/local/LICENSE'
Consider using the `--user` option or check the permissions.`

The library has installed though, and it does run.

**Comment by haizaar** [comment]
Can you please elaborate how to do install it? Is it within virtualenv? Otherwise you indeed need to pass `--user` usually. The following just worked for me (and on Python 3.8.2 as well):

```
$ /tmp $ python --version
Python 3.6.9
$ /tmp $ python -mvenv venv
$ /tmp $ source venv/bin/activate
(venv) $ /tmp $ pip install check-pipfile-lock
Collecting check-pipfile-lock
  Using cached https://files.pythonhosted.org/packages/70/57/966803b57b861e687b66ae6882278d8fad633a4790ebdfa88f9b37e475bc/check-pipfile-lock-0.0.4.tar.gz
  Installing build dependencies ... done
Collecting click (from check-pipfile-lock)
  Using cached https://files.pythonhosted.org/packages/d2/3d/fa76db83bf75c4f8d338c2fd15c8d33fdd7ad23a9b5e57eb6c5de26b430e/click-7.1.2-py2.py3-none-any.whl
Collecting clickclick (from check-pipfile-lock)
  Using cached https://files.pythonhosted.org/packages/b6/51/2b04f7a56dcbacc0e3a7cf726e1d88d28866bf488a7a0668582306e1e643/clickclick-1.2.2-py2.py3-none-any.whl
Collecting pipenv (from check-pipfile-lock)
  Using cached https://files.pythonhosted.org/packages/13/b4/3ffa55f77161cff9a5220f162670f7c5eb00df52e00939e203f601b0f579/pipenv-2018.11.26-py3-none-any.whl
Collecting PyYAML>=3.11 (from clickclick->check-pipfile-lock)
  Using cached https://files.pythonhosted.org/packages/64/c2/b80047c7ac2478f9501676c988a5411ed5572f35d1beff9cae07d321512c/PyYAML-5.3.1.tar.gz
Requirement already satisfied: setuptools>=36.2.1 in ./venv/lib/python3.6/site-packages (from pipenv->check-pipfile-lock) (40.6.2)
Collecting virtualenv (from pipenv->check-pipfile-lock)
  Using cached https://files.pythonhosted.org/packages/9b/67/f28095ba538be54fc48ec7774d5778a7246972cf8c701430ec0c96bf0860/virtualenv-20.0.20-py2.py3-none-any.whl
Collecting virtualenv-clone>=0.2.5 (from pipenv->check-pipfile-lock)
  Using cached https://files.pythonhosted.org/packages/83/b8/cd931487d250565392c39409117436d910232c8a3ac09ea2fb62a6c47bff/virtualenv_clone-0.5.4-py2.py3-none-any.whl
Collecting certifi (from pipenv->check-pipfile-lock)
  Using cached https://files.pythonhosted.org/packages/57/2b/26e37a4b034800c960a00c4e1b3d9ca5d7014e983e6e729e33ea2f36426c/certifi-2020.4.5.1-py2.py3-none-any.whl
Requirement already satisfied: pip>=9.0.1 in ./venv/lib/python3.6/site-packages (from pipenv->check-pipfile-lock) (18.1)
Collecting distlib<1,>=0.3.0 (from virtualenv->pipenv->check-pipfile-lock)
  Using cached https://files.pythonhosted.org/packages/7d/29/694a3a4d7c0e1aef76092e9167fbe372e0f7da055f5dcf4e1313ec21d96a/distlib-0.3.0.zip
Collecting six<2,>=1.9.0 (from virtualenv->pipenv->check-pipfile-lock)
  Using cached https://files.pythonhosted.org/packages/65/eb/1f97cb97bfc2390a276969c6fae16075da282f5058082d4cb10c6c5c1dba/six-1.14.0-py2.py3-none-any.whl
Collecting filelock<4,>=3.0.0 (from virtualenv->pipenv->check-pipfile-lock)
  Using cached https://files.pythonhosted.org/packages/93/83/71a2ee6158bb9f39a90c0dea1637f81d5eef866e188e1971a1b1ab01a35a/filelock-3.0.12-py3-none-any.whl
Collecting importlib-metadata<2,>=0.12; python_version < "3.8" (from virtualenv->pipenv->check-pipfile-lock)
  Using cached https://files.pythonhosted.org/packages/ad/e4/891bfcaf868ccabc619942f27940c77a8a4b45fd8367098955bb7e152fb1/importlib_metadata-1.6.0-py2.py3-none-any.whl
Collecting importlib-resources<2,>=1.0; python_version < "3.7" (from virtualenv->pipenv->check-pipfile-lock)
  Downloading https://files.pythonhosted.org/packages/7f/2d/88f166bcaadc09d9fdbf1c336ad118e01b7fe1155e15675e125be2ff1899/importlib_resources-1.5.0-py2.py3-none-any.whl
Collecting appdirs<2,>=1.4.3 (from virtualenv->pipenv->check-pipfile-lock)
  Using cached https://files.pythonhosted.org/packages/3b/00/2344469e2084fb287c2e0b57b72910309874c3245463acd6cf5e3db69324/appdirs-1.4.4-py2.py3-none-any.whl
Collecting zipp>=0.5 (from importlib-metadata<2,>=0.12; python_version < "3.8"->virtualenv->pipenv->check-pipfile-lock)
  Using cached https://files.pythonhosted.org/packages/b2/34/bfcb43cc0ba81f527bc4f40ef41ba2ff4080e047acb0586b56b3d017ace4/zipp-3.1.0-py3-none-any.whl
Installing collected packages: click, PyYAML, clickclick, distlib, six, filelock, zipp, importlib-metadata, importlib-resources, appdirs, virtualenv, virtualenv-clone, certifi, pipenv, check-pipfile-lock
  Running setup.py install for PyYAML ... done
  Running setup.py install for distlib ... done
  Running setup.py install for check-pipfile-lock ... done
Successfully installed PyYAML-5.3.1 appdirs-1.4.4 certifi-2020.4.5.1 check-pipfile-lock-0.0.4 click-7.1.2 clickclick-1.2.2 distlib-0.3.0 filelock-3.0.12 importlib-metadata-1.6.0 importlib-resources-1.5.0 pipenv-2018.11.26 six-1.14.0 virtualenv-20.0.20 virtualenv-clone-0.5.4 zipp-3.1.0
You are using pip version 18.1, however version 20.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.

```

**Comment by CloudySnake** [comment]
I am installing it on my global Python3 so it's available everywhere (much like I have with Black & Flake8).  I've never previously needed to use --user to get packages to install, though it's fair to say I don't install much outside of virtualenvs for obvious reasons.

I can install with pipenv without a problem, so seems best I close the ticket and go and see how it works in the pipeline. If that works then that's happy days.
